create table "public"."customer_user" (
    "id" uuid not null
);


alter table "public"."customer_user" enable row level security;

create table "public"."service_member_user" (
    "id" uuid not null
);


alter table "public"."service_member_user" enable row level security;

create table "public"."service_provider" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."service_provider" enable row level security;

create table "public"."service_provider_user" (
    "id" uuid not null
);


alter table "public"."service_provider_user" enable row level security;

create table "public"."user" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."user" enable row level security;

CREATE UNIQUE INDEX "User_pkey" ON public."user" USING btree (id);

CREATE UNIQUE INDEX customer_user_pkey ON public.customer_user USING btree (id);

CREATE UNIQUE INDEX service_member_user_pkey ON public.service_member_user USING btree (id);

CREATE UNIQUE INDEX service_provider_pkey ON public.service_provider USING btree (id);

CREATE UNIQUE INDEX service_provider_user_pkey ON public.service_provider_user USING btree (id);

alter table "public"."customer_user" add constraint "customer_user_pkey" PRIMARY KEY using index "customer_user_pkey";

alter table "public"."service_member_user" add constraint "service_member_user_pkey" PRIMARY KEY using index "service_member_user_pkey";

alter table "public"."service_provider" add constraint "service_provider_pkey" PRIMARY KEY using index "service_provider_pkey";

alter table "public"."service_provider_user" add constraint "service_provider_user_pkey" PRIMARY KEY using index "service_provider_user_pkey";

alter table "public"."user" add constraint "User_pkey" PRIMARY KEY using index "User_pkey";

alter table "public"."customer_user" add constraint "customer_user_id_fkey" FOREIGN KEY (id) REFERENCES "user"(id) not valid;

alter table "public"."customer_user" validate constraint "customer_user_id_fkey";

alter table "public"."service_member_user" add constraint "service_member_user_id_fkey" FOREIGN KEY (id) REFERENCES "user"(id) not valid;

alter table "public"."service_member_user" validate constraint "service_member_user_id_fkey";

alter table "public"."service_provider_user" add constraint "service_provider_user_id_fkey" FOREIGN KEY (id) REFERENCES "user"(id) not valid;

alter table "public"."service_provider_user" validate constraint "service_provider_user_id_fkey";

grant delete on table "public"."customer_user" to "anon";

grant insert on table "public"."customer_user" to "anon";

grant references on table "public"."customer_user" to "anon";

grant select on table "public"."customer_user" to "anon";

grant trigger on table "public"."customer_user" to "anon";

grant truncate on table "public"."customer_user" to "anon";

grant update on table "public"."customer_user" to "anon";

grant delete on table "public"."customer_user" to "authenticated";

grant insert on table "public"."customer_user" to "authenticated";

grant references on table "public"."customer_user" to "authenticated";

grant select on table "public"."customer_user" to "authenticated";

grant trigger on table "public"."customer_user" to "authenticated";

grant truncate on table "public"."customer_user" to "authenticated";

grant update on table "public"."customer_user" to "authenticated";

grant delete on table "public"."customer_user" to "service_role";

grant insert on table "public"."customer_user" to "service_role";

grant references on table "public"."customer_user" to "service_role";

grant select on table "public"."customer_user" to "service_role";

grant trigger on table "public"."customer_user" to "service_role";

grant truncate on table "public"."customer_user" to "service_role";

grant update on table "public"."customer_user" to "service_role";

grant delete on table "public"."service_member_user" to "anon";

grant insert on table "public"."service_member_user" to "anon";

grant references on table "public"."service_member_user" to "anon";

grant select on table "public"."service_member_user" to "anon";

grant trigger on table "public"."service_member_user" to "anon";

grant truncate on table "public"."service_member_user" to "anon";

grant update on table "public"."service_member_user" to "anon";

grant delete on table "public"."service_member_user" to "authenticated";

grant insert on table "public"."service_member_user" to "authenticated";

grant references on table "public"."service_member_user" to "authenticated";

grant select on table "public"."service_member_user" to "authenticated";

grant trigger on table "public"."service_member_user" to "authenticated";

grant truncate on table "public"."service_member_user" to "authenticated";

grant update on table "public"."service_member_user" to "authenticated";

grant delete on table "public"."service_member_user" to "service_role";

grant insert on table "public"."service_member_user" to "service_role";

grant references on table "public"."service_member_user" to "service_role";

grant select on table "public"."service_member_user" to "service_role";

grant trigger on table "public"."service_member_user" to "service_role";

grant truncate on table "public"."service_member_user" to "service_role";

grant update on table "public"."service_member_user" to "service_role";

grant delete on table "public"."service_provider" to "anon";

grant insert on table "public"."service_provider" to "anon";

grant references on table "public"."service_provider" to "anon";

grant select on table "public"."service_provider" to "anon";

grant trigger on table "public"."service_provider" to "anon";

grant truncate on table "public"."service_provider" to "anon";

grant update on table "public"."service_provider" to "anon";

grant delete on table "public"."service_provider" to "authenticated";

grant insert on table "public"."service_provider" to "authenticated";

grant references on table "public"."service_provider" to "authenticated";

grant select on table "public"."service_provider" to "authenticated";

grant trigger on table "public"."service_provider" to "authenticated";

grant truncate on table "public"."service_provider" to "authenticated";

grant update on table "public"."service_provider" to "authenticated";

grant delete on table "public"."service_provider" to "service_role";

grant insert on table "public"."service_provider" to "service_role";

grant references on table "public"."service_provider" to "service_role";

grant select on table "public"."service_provider" to "service_role";

grant trigger on table "public"."service_provider" to "service_role";

grant truncate on table "public"."service_provider" to "service_role";

grant update on table "public"."service_provider" to "service_role";

grant delete on table "public"."service_provider_user" to "anon";

grant insert on table "public"."service_provider_user" to "anon";

grant references on table "public"."service_provider_user" to "anon";

grant select on table "public"."service_provider_user" to "anon";

grant trigger on table "public"."service_provider_user" to "anon";

grant truncate on table "public"."service_provider_user" to "anon";

grant update on table "public"."service_provider_user" to "anon";

grant delete on table "public"."service_provider_user" to "authenticated";

grant insert on table "public"."service_provider_user" to "authenticated";

grant references on table "public"."service_provider_user" to "authenticated";

grant select on table "public"."service_provider_user" to "authenticated";

grant trigger on table "public"."service_provider_user" to "authenticated";

grant truncate on table "public"."service_provider_user" to "authenticated";

grant update on table "public"."service_provider_user" to "authenticated";

grant delete on table "public"."service_provider_user" to "service_role";

grant insert on table "public"."service_provider_user" to "service_role";

grant references on table "public"."service_provider_user" to "service_role";

grant select on table "public"."service_provider_user" to "service_role";

grant trigger on table "public"."service_provider_user" to "service_role";

grant truncate on table "public"."service_provider_user" to "service_role";

grant update on table "public"."service_provider_user" to "service_role";

grant delete on table "public"."user" to "anon";

grant insert on table "public"."user" to "anon";

grant references on table "public"."user" to "anon";

grant select on table "public"."user" to "anon";

grant trigger on table "public"."user" to "anon";

grant truncate on table "public"."user" to "anon";

grant update on table "public"."user" to "anon";

grant delete on table "public"."user" to "authenticated";

grant insert on table "public"."user" to "authenticated";

grant references on table "public"."user" to "authenticated";

grant select on table "public"."user" to "authenticated";

grant trigger on table "public"."user" to "authenticated";

grant truncate on table "public"."user" to "authenticated";

grant update on table "public"."user" to "authenticated";

grant delete on table "public"."user" to "service_role";

grant insert on table "public"."user" to "service_role";

grant references on table "public"."user" to "service_role";

grant select on table "public"."user" to "service_role";

grant trigger on table "public"."user" to "service_role";

grant truncate on table "public"."user" to "service_role";

grant update on table "public"."user" to "service_role";


