create table "public"."monthly_spotlight" (
    "id" bigint generated by default as identity not null,
    "order" smallint not null default '1'::smallint,
    "service_provider" uuid,
    "service_provider_member" uuid
);


alter table "public"."monthly_spotlight" enable row level security;

CREATE UNIQUE INDEX monthly_spotlight_pkey ON public.monthly_spotlight USING btree (id);

alter table "public"."monthly_spotlight" add constraint "monthly_spotlight_pkey" PRIMARY KEY using index "monthly_spotlight_pkey";

alter table "public"."monthly_spotlight" add constraint "monthly_spotlight_service_provider_fkey" FOREIGN KEY (service_provider) REFERENCES service_provider(id) not valid;

alter table "public"."monthly_spotlight" validate constraint "monthly_spotlight_service_provider_fkey";

alter table "public"."monthly_spotlight" add constraint "monthly_spotlight_service_provider_member_fkey" FOREIGN KEY (service_provider_member) REFERENCES service_provider_member(id) not valid;

alter table "public"."monthly_spotlight" validate constraint "monthly_spotlight_service_provider_member_fkey";

grant delete on table "public"."monthly_spotlight" to "anon";

grant insert on table "public"."monthly_spotlight" to "anon";

grant references on table "public"."monthly_spotlight" to "anon";

grant select on table "public"."monthly_spotlight" to "anon";

grant trigger on table "public"."monthly_spotlight" to "anon";

grant truncate on table "public"."monthly_spotlight" to "anon";

grant update on table "public"."monthly_spotlight" to "anon";

grant delete on table "public"."monthly_spotlight" to "authenticated";

grant insert on table "public"."monthly_spotlight" to "authenticated";

grant references on table "public"."monthly_spotlight" to "authenticated";

grant select on table "public"."monthly_spotlight" to "authenticated";

grant trigger on table "public"."monthly_spotlight" to "authenticated";

grant truncate on table "public"."monthly_spotlight" to "authenticated";

grant update on table "public"."monthly_spotlight" to "authenticated";

grant delete on table "public"."monthly_spotlight" to "service_role";

grant insert on table "public"."monthly_spotlight" to "service_role";

grant references on table "public"."monthly_spotlight" to "service_role";

grant select on table "public"."monthly_spotlight" to "service_role";

grant trigger on table "public"."monthly_spotlight" to "service_role";

grant truncate on table "public"."monthly_spotlight" to "service_role";

grant update on table "public"."monthly_spotlight" to "service_role";

create policy "Anyone can SELECT"
on "public"."monthly_spotlight"
as permissive
for select
to public
using (true);



