name: Deploy (Dev)

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        SUPABASE_DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
        SUPABASE_PROJECT_ID: ${{ secrets.STAGING_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Supabase Setup
        run: supabase link --project-ref $SUPABASE_PROJECT_ID

      - name: Write db to Supabase Dev
        run: supabase db push

      - name: Deploy edge functions to Supabase Dev
        run: supabase functions deploy

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('app/package-lock.json') }}
          restore-keys: npm-

      - name: npm Install
        working-directory: ./app
        run: npm install

      - name: Generate Types
        working-directory: ./app
        run: npx supabase gen types typescript --linked --schema public,storage > src/types/supabase.ts

      - name: Build App
        working-directory: ./app
        run: npm run build-dev

      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: app.2dingit.com
          username: www-data
          key: ${{ secrets.SSH_PRIVATE_KEY_APP_SERVER }}
          source: "app/dist/app/browser/*"
          target: "/var/www/dev/${{ github.sha }}"
          strip_components: 4
      
      - name: Set up symbolic link alias
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: app.2dingit.com
          username: www-data
          key: ${{ secrets.SSH_PRIVATE_KEY_APP_SERVER }}
          script: rm /var/www/dev.app.2dingit.com && ln -s /var/www/dev/${{ github.sha }} /var/www/dev.app.2dingit.com