name: Deploy (Dev)

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        SUPABASE_DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
        SUPABASE_PROJECT_ID: ${{ secrets.STAGING_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Supabase Setup
        run: supabase link --project-ref $SUPABASE_PROJECT_ID

      - name: Write db to Supabase Dev
        run: supabase db push

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('app/package-lock.json') }}
          restore-keys: npm-

      - name: npm Install
        working-directory: ./app
        run: npm install

      - name: Generate Types
        working-directory: ./app
        run: npx supabase gen types typescript --project-id "$PROJECT_REF" --schema public > types/supabase.ts

      - name: Build App
        working-directory: ./app
        run: npx build --configuration=development
